// Code generated by gen-tuple; DO NOT EDIT.

package tuple7

import "testing"

func TestTuple(t *testing.T) {
	// Pack
	tuple := Pack(1, 2, 3, 4, 5, 6, 7)
	if tuple.A != 1 {
		t.Errorf("tuple.A must be 1, but %d", tuple.A)
	}
	if tuple.B != 2 {
		t.Errorf("tuple.B must be 2, but %d", tuple.B)
	}
	if tuple.C != 3 {
		t.Errorf("tuple.C must be 3, but %d", tuple.C)
	}
	if tuple.D != 4 {
		t.Errorf("tuple.D must be 4, but %d", tuple.D)
	}
	if tuple.E != 5 {
		t.Errorf("tuple.E must be 5, but %d", tuple.E)
	}
	if tuple.F != 6 {
		t.Errorf("tuple.F must be 6, but %d", tuple.F)
	}
	if tuple.G != 7 {
		t.Errorf("tuple.G must be 7, but %d", tuple.G)
	}

	// Unpack
	vA, vB, vC, vD, vE, vF, vG := tuple.Unpack()
	if vA != 1 {
		t.Errorf("vA must be 1, but %d", vA)
	}
	if vB != 2 {
		t.Errorf("vB must be 2, but %d", vB)
	}
	if vC != 3 {
		t.Errorf("vC must be 3, but %d", vC)
	}
	if vD != 4 {
		t.Errorf("vD must be 4, but %d", vD)
	}
	if vE != 5 {
		t.Errorf("vE must be 5, but %d", vE)
	}
	if vF != 6 {
		t.Errorf("vF must be 6, but %d", vF)
	}
	if vG != 7 {
		t.Errorf("vG must be 7, but %d", vG)
	}
}
