// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple7 provides a simple, general-purpose tuple type for holding seven ordered values.
package tuple7

import "fmt"

// Tuple is a generic container that holds exactly seven elements.
type Tuple[A, B, C, D, E, F, G any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
}

// Pack creates a new Tuple containing the seven supplied values.
func Pack[A, B, C, D, E, F, G any](a A, b B, c C, d D, e E, f F, g G) Tuple[A, B, C, D, E, F, G] {
	return Tuple[A, B, C, D, E, F, G]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g,
	}
}

// Unpack returns the seven elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G]) Unpack() (A, B, C, D, E, F, G) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G}
}
