// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple17 provides a simple, general-purpose tuple type for holding seventeen ordered values.
package tuple17

import "fmt"

// Tuple is a generic container that holds exactly seventeen elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
}

// Pack creates a new Tuple containing the seventeen supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q) Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k, L: l, M: m, N: n, O: o, P: p, Q: q,
	}
}

// Unpack returns the seventeen elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]) Unpack() (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q}
}
