// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple14 provides a simple, general-purpose tuple type for holding fourteen ordered values.
package tuple14

import "fmt"

// Tuple is a generic container that holds exactly fourteen elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
}

// Pack creates a new Tuple containing the fourteen supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K, L, M, N any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N) Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k, L: l, M: m, N: n,
	}
}

// Unpack returns the fourteen elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) Unpack() (A, B, C, D, E, F, G, H, I, J, K, L, M, N) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N}
}
