// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple14getter

package tuple14

// GetA returns t.A.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetD() D { return t.D }

// GetE returns t.E.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetE() E { return t.E }

// GetF returns t.F.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetF() F { return t.F }

// GetG returns t.G.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetG() G { return t.G }

// GetH returns t.H.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetH() H { return t.H }

// GetI returns t.I.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetI() I { return t.I }

// GetJ returns t.J.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetJ() J { return t.J }

// GetK returns t.K.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetK() K { return t.K }

// GetL returns t.L.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetL() L { return t.L }

// GetM returns t.M.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetM() M { return t.M }

// GetN returns t.N.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) GetN() N { return t.N }
