// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple4 provides a simple, general-purpose tuple type for holding four ordered values.
package tuple4

import "fmt"

// Tuple is a generic container that holds exactly four elements.
type Tuple[A, B, C, D any] struct {
	A A
	B B
	C C
	D D
}

// Pack creates a new Tuple containing the four supplied values.
func Pack[A, B, C, D any](a A, b B, c C, d D) Tuple[A, B, C, D] {
	return Tuple[A, B, C, D]{
		A: a, B: b, C: c, D: d,
	}
}

// Unpack returns the four elements contained in the tuple.
func (t Tuple[A, B, C, D]) Unpack() (A, B, C, D) {
	return t.A, t.B, t.C, t.D
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v)", t.A, t.B, t.C, t.D)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D}
}
