// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build go1.22

package tuple4

import "cmp"

// Compare performs a lexicographical comparison of two tuples, comparing elements in order: A, then B, then C, then D.
func Compare[A, B, C, D cmp.Ordered](a, b Tuple[A, B, C, D]) int {
	if c := cmp.Compare(a.A, b.A); c != 0 {
		return c
	}
	if c := cmp.Compare(a.B, b.B); c != 0 {
		return c
	}
	if c := cmp.Compare(a.C, b.C); c != 0 {
		return c
	}
	return cmp.Compare(a.D, b.D)
}
