// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple4getter

package tuple4

// GetA returns t.A.
func (t Tuple[A, B, C, D]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D]) GetD() D { return t.D }
