// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple15 provides a simple, general-purpose tuple type for holding fifteen ordered values.
package tuple15

import "fmt"

// Tuple is a generic container that holds exactly fifteen elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
}

// Pack creates a new Tuple containing the fifteen supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O) Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k, L: l, M: m, N: n, O: o,
	}
}

// Unpack returns the fifteen elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) Unpack() (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O}
}
