// Code generated by gen-tuple; DO NOT EDIT.

package tuple15

import "testing"

func TestTuple(t *testing.T) {
	// Pack
	tuple := Pack(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
	if tuple.A != 1 {
		t.Errorf("tuple.A must be 1, but %d", tuple.A)
	}
	if tuple.B != 2 {
		t.Errorf("tuple.B must be 2, but %d", tuple.B)
	}
	if tuple.C != 3 {
		t.Errorf("tuple.C must be 3, but %d", tuple.C)
	}
	if tuple.D != 4 {
		t.Errorf("tuple.D must be 4, but %d", tuple.D)
	}
	if tuple.E != 5 {
		t.Errorf("tuple.E must be 5, but %d", tuple.E)
	}
	if tuple.F != 6 {
		t.Errorf("tuple.F must be 6, but %d", tuple.F)
	}
	if tuple.G != 7 {
		t.Errorf("tuple.G must be 7, but %d", tuple.G)
	}
	if tuple.H != 8 {
		t.Errorf("tuple.H must be 8, but %d", tuple.H)
	}
	if tuple.I != 9 {
		t.Errorf("tuple.I must be 9, but %d", tuple.I)
	}
	if tuple.J != 10 {
		t.Errorf("tuple.J must be 10, but %d", tuple.J)
	}
	if tuple.K != 11 {
		t.Errorf("tuple.K must be 11, but %d", tuple.K)
	}
	if tuple.L != 12 {
		t.Errorf("tuple.L must be 12, but %d", tuple.L)
	}
	if tuple.M != 13 {
		t.Errorf("tuple.M must be 13, but %d", tuple.M)
	}
	if tuple.N != 14 {
		t.Errorf("tuple.N must be 14, but %d", tuple.N)
	}
	if tuple.O != 15 {
		t.Errorf("tuple.O must be 15, but %d", tuple.O)
	}

	// Unpack
	vA, vB, vC, vD, vE, vF, vG, vH, vI, vJ, vK, vL, vM, vN, vO := tuple.Unpack()
	if vA != 1 {
		t.Errorf("vA must be 1, but %d", vA)
	}
	if vB != 2 {
		t.Errorf("vB must be 2, but %d", vB)
	}
	if vC != 3 {
		t.Errorf("vC must be 3, but %d", vC)
	}
	if vD != 4 {
		t.Errorf("vD must be 4, but %d", vD)
	}
	if vE != 5 {
		t.Errorf("vE must be 5, but %d", vE)
	}
	if vF != 6 {
		t.Errorf("vF must be 6, but %d", vF)
	}
	if vG != 7 {
		t.Errorf("vG must be 7, but %d", vG)
	}
	if vH != 8 {
		t.Errorf("vH must be 8, but %d", vH)
	}
	if vI != 9 {
		t.Errorf("vI must be 9, but %d", vI)
	}
	if vJ != 10 {
		t.Errorf("vJ must be 10, but %d", vJ)
	}
	if vK != 11 {
		t.Errorf("vK must be 11, but %d", vK)
	}
	if vL != 12 {
		t.Errorf("vL must be 12, but %d", vL)
	}
	if vM != 13 {
		t.Errorf("vM must be 13, but %d", vM)
	}
	if vN != 14 {
		t.Errorf("vN must be 14, but %d", vN)
	}
	if vO != 15 {
		t.Errorf("vO must be 15, but %d", vO)
	}
}
