// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build go1.22

package tuple15

import "cmp"

// Compare performs a lexicographical comparison of two tuples, comparing elements in order: A, then B, then C, then D, then E, then F, then G, then H, then I, then J, then K, then L, then M, then N, then O.
func Compare[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O cmp.Ordered](a, b Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) int {
	if c := cmp.Compare(a.A, b.A); c != 0 {
		return c
	}
	if c := cmp.Compare(a.B, b.B); c != 0 {
		return c
	}
	if c := cmp.Compare(a.C, b.C); c != 0 {
		return c
	}
	if c := cmp.Compare(a.D, b.D); c != 0 {
		return c
	}
	if c := cmp.Compare(a.E, b.E); c != 0 {
		return c
	}
	if c := cmp.Compare(a.F, b.F); c != 0 {
		return c
	}
	if c := cmp.Compare(a.G, b.G); c != 0 {
		return c
	}
	if c := cmp.Compare(a.H, b.H); c != 0 {
		return c
	}
	if c := cmp.Compare(a.I, b.I); c != 0 {
		return c
	}
	if c := cmp.Compare(a.J, b.J); c != 0 {
		return c
	}
	if c := cmp.Compare(a.K, b.K); c != 0 {
		return c
	}
	if c := cmp.Compare(a.L, b.L); c != 0 {
		return c
	}
	if c := cmp.Compare(a.M, b.M); c != 0 {
		return c
	}
	if c := cmp.Compare(a.N, b.N); c != 0 {
		return c
	}
	return cmp.Compare(a.O, b.O)
}
