// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple27 provides a simple, general-purpose tuple type for holding twenty-seven ordered values.
package tuple27

import "fmt"

// Tuple is a generic container that holds exactly twenty-seven elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA any] struct {
	A  A
	B  B
	C  C
	D  D
	E  E
	F  F
	G  G
	H  H
	I  I
	J  J
	K  K
	L  L
	M  M
	N  N
	O  O
	P  P
	Q  Q
	R  R
	S  S
	T  T
	U  U
	V  V
	W  W
	X  X
	Y  Y
	Z  Z
	AA AA
}

// Pack creates a new Tuple containing the twenty-seven supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T, u U, v V, w W, x X, y Y, z Z, aa AA) Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k, L: l, M: m, N: n, O: o, P: p, Q: q, R: r, S: s, T: t, U: u, V: v, W: w, X: x, Y: y, Z: z, AA: aa,
	}
}

// Unpack returns the twenty-seven elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA]) Unpack() (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q, t.R, t.S, t.T, t.U, t.V, t.W, t.X, t.Y, t.Z, t.AA
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q, t.R, t.S, t.T, t.U, t.V, t.W, t.X, t.Y, t.Z, t.AA)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q, t.R, t.S, t.T, t.U, t.V, t.W, t.X, t.Y, t.Z, t.AA}
}
