// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple11 provides a simple, general-purpose tuple type for holding eleven ordered values.
package tuple11

import "fmt"

// Tuple is a generic container that holds exactly eleven elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
}

// Pack creates a new Tuple containing the eleven supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K) Tuple[A, B, C, D, E, F, G, H, I, J, K] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k,
	}
}

// Unpack returns the eleven elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K]) Unpack() (A, B, C, D, E, F, G, H, I, J, K) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K}
}
