// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple12 provides a simple, general-purpose tuple type for holding twelve ordered values.
package tuple12

import "fmt"

// Tuple is a generic container that holds exactly twelve elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K, L any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
}

// Pack creates a new Tuple containing the twelve supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K, L any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L) Tuple[A, B, C, D, E, F, G, H, I, J, K, L] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K, L]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k, L: l,
	}
}

// Unpack returns the twelve elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L]) Unpack() (A, B, C, D, E, F, G, H, I, J, K, L) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L}
}
