// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple16getter

package tuple16

// GetA returns t.A.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetD() D { return t.D }

// GetE returns t.E.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetE() E { return t.E }

// GetF returns t.F.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetF() F { return t.F }

// GetG returns t.G.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetG() G { return t.G }

// GetH returns t.H.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetH() H { return t.H }

// GetI returns t.I.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetI() I { return t.I }

// GetJ returns t.J.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetJ() J { return t.J }

// GetK returns t.K.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetK() K { return t.K }

// GetL returns t.L.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetL() L { return t.L }

// GetM returns t.M.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetM() M { return t.M }

// GetN returns t.N.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetN() N { return t.N }

// GetO returns t.O.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetO() O { return t.O }

// GetP returns t.P.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) GetP() P { return t.P }
