// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple9getter

package tuple9

// GetA returns t.A.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetD() D { return t.D }

// GetE returns t.E.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetE() E { return t.E }

// GetF returns t.F.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetF() F { return t.F }

// GetG returns t.G.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetG() G { return t.G }

// GetH returns t.H.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetH() H { return t.H }

// GetI returns t.I.
func (t Tuple[A, B, C, D, E, F, G, H, I]) GetI() I { return t.I }
