// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple9 provides a simple, general-purpose tuple type for holding nine ordered values.
package tuple9

import "fmt"

// Tuple is a generic container that holds exactly nine elements.
type Tuple[A, B, C, D, E, F, G, H, I any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
}

// Pack creates a new Tuple containing the nine supplied values.
func Pack[A, B, C, D, E, F, G, H, I any](a A, b B, c C, d D, e E, f F, g G, h H, i I) Tuple[A, B, C, D, E, F, G, H, I] {
	return Tuple[A, B, C, D, E, F, G, H, I]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i,
	}
}

// Unpack returns the nine elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I]) Unpack() (A, B, C, D, E, F, G, H, I) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I}
}
