// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple10 provides a simple, general-purpose tuple type for holding ten ordered values.
package tuple10

import "fmt"

// Tuple is a generic container that holds exactly ten elements.
type Tuple[A, B, C, D, E, F, G, H, I, J any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
}

// Pack creates a new Tuple containing the ten supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J) Tuple[A, B, C, D, E, F, G, H, I, J] {
	return Tuple[A, B, C, D, E, F, G, H, I, J]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j,
	}
}

// Unpack returns the ten elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J]) Unpack() (A, B, C, D, E, F, G, H, I, J) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J}
}
