// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple5 provides a simple, general-purpose tuple type for holding five ordered values.
package tuple5

import "fmt"

// Tuple is a generic container that holds exactly five elements.
type Tuple[A, B, C, D, E any] struct {
	A A
	B B
	C C
	D D
	E E
}

// Pack creates a new Tuple containing the five supplied values.
func Pack[A, B, C, D, E any](a A, b B, c C, d D, e E) Tuple[A, B, C, D, E] {
	return Tuple[A, B, C, D, E]{
		A: a, B: b, C: c, D: d, E: e,
	}
}

// Unpack returns the five elements contained in the tuple.
func (t Tuple[A, B, C, D, E]) Unpack() (A, B, C, D, E) {
	return t.A, t.B, t.C, t.D, t.E
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E}
}
