// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple5getter

package tuple5

// GetA returns t.A.
func (t Tuple[A, B, C, D, E]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D, E]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D, E]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D, E]) GetD() D { return t.D }

// GetE returns t.E.
func (t Tuple[A, B, C, D, E]) GetE() E { return t.E }
