// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple13 provides a simple, general-purpose tuple type for holding thirteen ordered values.
package tuple13

import "fmt"

// Tuple is a generic container that holds exactly thirteen elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
}

// Pack creates a new Tuple containing the thirteen supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K, L, M any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M) Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k, L: l, M: m,
	}
}

// Unpack returns the thirteen elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) Unpack() (A, B, C, D, E, F, G, H, I, J, K, L, M) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M}
}
