// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple13getter

package tuple13

// GetA returns t.A.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetD() D { return t.D }

// GetE returns t.E.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetE() E { return t.E }

// GetF returns t.F.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetF() F { return t.F }

// GetG returns t.G.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetG() G { return t.G }

// GetH returns t.H.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetH() H { return t.H }

// GetI returns t.I.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetI() I { return t.I }

// GetJ returns t.J.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetJ() J { return t.J }

// GetK returns t.K.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetK() K { return t.K }

// GetL returns t.L.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetL() L { return t.L }

// GetM returns t.M.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M]) GetM() M { return t.M }
