// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple3 provides a simple, general-purpose tuple type for holding three ordered values.
package tuple3

import "fmt"

// Tuple is a generic container that holds exactly three elements.
type Tuple[A, B, C any] struct {
	A A
	B B
	C C
}

// Pack creates a new Tuple containing the three supplied values.
func Pack[A, B, C any](a A, b B, c C) Tuple[A, B, C] {
	return Tuple[A, B, C]{
		A: a, B: b, C: c,
	}
}

// Unpack returns the three elements contained in the tuple.
func (t Tuple[A, B, C]) Unpack() (A, B, C) {
	return t.A, t.B, t.C
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C]) String() string {
	return fmt.Sprintf("(%v, %v, %v)", t.A, t.B, t.C)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C]) ToSlice() []any {
	return []any{t.A, t.B, t.C}
}
