// Code generated by gen-tuple; DO NOT EDIT.

package tuple3

import "testing"

func TestTuple(t *testing.T) {
	// Pack
	tuple := Pack(1, 2, 3)
	if tuple.A != 1 {
		t.Errorf("tuple.A must be 1, but %d", tuple.A)
	}
	if tuple.B != 2 {
		t.Errorf("tuple.B must be 2, but %d", tuple.B)
	}
	if tuple.C != 3 {
		t.Errorf("tuple.C must be 3, but %d", tuple.C)
	}

	// Unpack
	vA, vB, vC := tuple.Unpack()
	if vA != 1 {
		t.Errorf("vA must be 1, but %d", vA)
	}
	if vB != 2 {
		t.Errorf("vB must be 2, but %d", vB)
	}
	if vC != 3 {
		t.Errorf("vC must be 3, but %d", vC)
	}
}
