// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple3getter

package tuple3

// GetA returns t.A.
func (t Tuple[A, B, C]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C]) GetC() C { return t.C }
