// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple18getter

package tuple18

// GetA returns t.A.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetD() D { return t.D }

// GetE returns t.E.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetE() E { return t.E }

// GetF returns t.F.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetF() F { return t.F }

// GetG returns t.G.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetG() G { return t.G }

// GetH returns t.H.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetH() H { return t.H }

// GetI returns t.I.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetI() I { return t.I }

// GetJ returns t.J.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetJ() J { return t.J }

// GetK returns t.K.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetK() K { return t.K }

// GetL returns t.L.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetL() L { return t.L }

// GetM returns t.M.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetM() M { return t.M }

// GetN returns t.N.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetN() N { return t.N }

// GetO returns t.O.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetO() O { return t.O }

// GetP returns t.P.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetP() P { return t.P }

// GetQ returns t.Q.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetQ() Q { return t.Q }

// GetR returns t.R.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]) GetR() R { return t.R }
