// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple8 provides a simple, general-purpose tuple type for holding eight ordered values.
package tuple8

import "fmt"

// Tuple is a generic container that holds exactly eight elements.
type Tuple[A, B, C, D, E, F, G, H any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
}

// Pack creates a new Tuple containing the eight supplied values.
func Pack[A, B, C, D, E, F, G, H any](a A, b B, c C, d D, e E, f F, g G, h H) Tuple[A, B, C, D, E, F, G, H] {
	return Tuple[A, B, C, D, E, F, G, H]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h,
	}
}

// Unpack returns the eight elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H]) Unpack() (A, B, C, D, E, F, G, H) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H}
}
