// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple8getter

package tuple8

// GetA returns t.A.
func (t Tuple[A, B, C, D, E, F, G, H]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B, C, D, E, F, G, H]) GetB() B { return t.B }

// GetC returns t.C.
func (t Tuple[A, B, C, D, E, F, G, H]) GetC() C { return t.C }

// GetD returns t.D.
func (t Tuple[A, B, C, D, E, F, G, H]) GetD() D { return t.D }

// GetE returns t.E.
func (t Tuple[A, B, C, D, E, F, G, H]) GetE() E { return t.E }

// GetF returns t.F.
func (t Tuple[A, B, C, D, E, F, G, H]) GetF() F { return t.F }

// GetG returns t.G.
func (t Tuple[A, B, C, D, E, F, G, H]) GetG() G { return t.G }

// GetH returns t.H.
func (t Tuple[A, B, C, D, E, F, G, H]) GetH() H { return t.H }
