// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build go1.22

package tuple26

import "cmp"

// Compare performs a lexicographical comparison of two tuples, comparing elements in order: A, then B, then C, then D, then E, then F, then G, then H, then I, then J, then K, then L, then M, then N, then O, then P, then Q, then R, then S, then T, then U, then V, then W, then X, then Y, then Z.
func Compare[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z cmp.Ordered](a, b Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]) int {
	if c := cmp.Compare(a.A, b.A); c != 0 {
		return c
	}
	if c := cmp.Compare(a.B, b.B); c != 0 {
		return c
	}
	if c := cmp.Compare(a.C, b.C); c != 0 {
		return c
	}
	if c := cmp.Compare(a.D, b.D); c != 0 {
		return c
	}
	if c := cmp.Compare(a.E, b.E); c != 0 {
		return c
	}
	if c := cmp.Compare(a.F, b.F); c != 0 {
		return c
	}
	if c := cmp.Compare(a.G, b.G); c != 0 {
		return c
	}
	if c := cmp.Compare(a.H, b.H); c != 0 {
		return c
	}
	if c := cmp.Compare(a.I, b.I); c != 0 {
		return c
	}
	if c := cmp.Compare(a.J, b.J); c != 0 {
		return c
	}
	if c := cmp.Compare(a.K, b.K); c != 0 {
		return c
	}
	if c := cmp.Compare(a.L, b.L); c != 0 {
		return c
	}
	if c := cmp.Compare(a.M, b.M); c != 0 {
		return c
	}
	if c := cmp.Compare(a.N, b.N); c != 0 {
		return c
	}
	if c := cmp.Compare(a.O, b.O); c != 0 {
		return c
	}
	if c := cmp.Compare(a.P, b.P); c != 0 {
		return c
	}
	if c := cmp.Compare(a.Q, b.Q); c != 0 {
		return c
	}
	if c := cmp.Compare(a.R, b.R); c != 0 {
		return c
	}
	if c := cmp.Compare(a.S, b.S); c != 0 {
		return c
	}
	if c := cmp.Compare(a.T, b.T); c != 0 {
		return c
	}
	if c := cmp.Compare(a.U, b.U); c != 0 {
		return c
	}
	if c := cmp.Compare(a.V, b.V); c != 0 {
		return c
	}
	if c := cmp.Compare(a.W, b.W); c != 0 {
		return c
	}
	if c := cmp.Compare(a.X, b.X); c != 0 {
		return c
	}
	if c := cmp.Compare(a.Y, b.Y); c != 0 {
		return c
	}
	return cmp.Compare(a.Z, b.Z)
}
