// Code generated by gen-tuple; DO NOT EDIT.

package tuple26

import "testing"

func TestTuple(t *testing.T) {
	// Pack
	tuple := Pack(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26)
	if tuple.A != 1 {
		t.Errorf("tuple.A must be 1, but %d", tuple.A)
	}
	if tuple.B != 2 {
		t.Errorf("tuple.B must be 2, but %d", tuple.B)
	}
	if tuple.C != 3 {
		t.Errorf("tuple.C must be 3, but %d", tuple.C)
	}
	if tuple.D != 4 {
		t.Errorf("tuple.D must be 4, but %d", tuple.D)
	}
	if tuple.E != 5 {
		t.Errorf("tuple.E must be 5, but %d", tuple.E)
	}
	if tuple.F != 6 {
		t.Errorf("tuple.F must be 6, but %d", tuple.F)
	}
	if tuple.G != 7 {
		t.Errorf("tuple.G must be 7, but %d", tuple.G)
	}
	if tuple.H != 8 {
		t.Errorf("tuple.H must be 8, but %d", tuple.H)
	}
	if tuple.I != 9 {
		t.Errorf("tuple.I must be 9, but %d", tuple.I)
	}
	if tuple.J != 10 {
		t.Errorf("tuple.J must be 10, but %d", tuple.J)
	}
	if tuple.K != 11 {
		t.Errorf("tuple.K must be 11, but %d", tuple.K)
	}
	if tuple.L != 12 {
		t.Errorf("tuple.L must be 12, but %d", tuple.L)
	}
	if tuple.M != 13 {
		t.Errorf("tuple.M must be 13, but %d", tuple.M)
	}
	if tuple.N != 14 {
		t.Errorf("tuple.N must be 14, but %d", tuple.N)
	}
	if tuple.O != 15 {
		t.Errorf("tuple.O must be 15, but %d", tuple.O)
	}
	if tuple.P != 16 {
		t.Errorf("tuple.P must be 16, but %d", tuple.P)
	}
	if tuple.Q != 17 {
		t.Errorf("tuple.Q must be 17, but %d", tuple.Q)
	}
	if tuple.R != 18 {
		t.Errorf("tuple.R must be 18, but %d", tuple.R)
	}
	if tuple.S != 19 {
		t.Errorf("tuple.S must be 19, but %d", tuple.S)
	}
	if tuple.T != 20 {
		t.Errorf("tuple.T must be 20, but %d", tuple.T)
	}
	if tuple.U != 21 {
		t.Errorf("tuple.U must be 21, but %d", tuple.U)
	}
	if tuple.V != 22 {
		t.Errorf("tuple.V must be 22, but %d", tuple.V)
	}
	if tuple.W != 23 {
		t.Errorf("tuple.W must be 23, but %d", tuple.W)
	}
	if tuple.X != 24 {
		t.Errorf("tuple.X must be 24, but %d", tuple.X)
	}
	if tuple.Y != 25 {
		t.Errorf("tuple.Y must be 25, but %d", tuple.Y)
	}
	if tuple.Z != 26 {
		t.Errorf("tuple.Z must be 26, but %d", tuple.Z)
	}

	// Unpack
	vA, vB, vC, vD, vE, vF, vG, vH, vI, vJ, vK, vL, vM, vN, vO, vP, vQ, vR, vS, vT, vU, vV, vW, vX, vY, vZ := tuple.Unpack()
	if vA != 1 {
		t.Errorf("vA must be 1, but %d", vA)
	}
	if vB != 2 {
		t.Errorf("vB must be 2, but %d", vB)
	}
	if vC != 3 {
		t.Errorf("vC must be 3, but %d", vC)
	}
	if vD != 4 {
		t.Errorf("vD must be 4, but %d", vD)
	}
	if vE != 5 {
		t.Errorf("vE must be 5, but %d", vE)
	}
	if vF != 6 {
		t.Errorf("vF must be 6, but %d", vF)
	}
	if vG != 7 {
		t.Errorf("vG must be 7, but %d", vG)
	}
	if vH != 8 {
		t.Errorf("vH must be 8, but %d", vH)
	}
	if vI != 9 {
		t.Errorf("vI must be 9, but %d", vI)
	}
	if vJ != 10 {
		t.Errorf("vJ must be 10, but %d", vJ)
	}
	if vK != 11 {
		t.Errorf("vK must be 11, but %d", vK)
	}
	if vL != 12 {
		t.Errorf("vL must be 12, but %d", vL)
	}
	if vM != 13 {
		t.Errorf("vM must be 13, but %d", vM)
	}
	if vN != 14 {
		t.Errorf("vN must be 14, but %d", vN)
	}
	if vO != 15 {
		t.Errorf("vO must be 15, but %d", vO)
	}
	if vP != 16 {
		t.Errorf("vP must be 16, but %d", vP)
	}
	if vQ != 17 {
		t.Errorf("vQ must be 17, but %d", vQ)
	}
	if vR != 18 {
		t.Errorf("vR must be 18, but %d", vR)
	}
	if vS != 19 {
		t.Errorf("vS must be 19, but %d", vS)
	}
	if vT != 20 {
		t.Errorf("vT must be 20, but %d", vT)
	}
	if vU != 21 {
		t.Errorf("vU must be 21, but %d", vU)
	}
	if vV != 22 {
		t.Errorf("vV must be 22, but %d", vV)
	}
	if vW != 23 {
		t.Errorf("vW must be 23, but %d", vW)
	}
	if vX != 24 {
		t.Errorf("vX must be 24, but %d", vX)
	}
	if vY != 25 {
		t.Errorf("vY must be 25, but %d", vY)
	}
	if vZ != 26 {
		t.Errorf("vZ must be 26, but %d", vZ)
	}
}
