// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple19 provides a simple, general-purpose tuple type for holding nineteen ordered values.
package tuple19

import "fmt"

// Tuple is a generic container that holds exactly nineteen elements.
type Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
}

// Pack creates a new Tuple containing the nineteen supplied values.
func Pack[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S) Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S] {
	return Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]{
		A: a, B: b, C: c, D: d, E: e, F: f, G: g, H: h, I: i, J: j, K: k, L: l, M: m, N: n, O: o, P: p, Q: q, R: r, S: s,
	}
}

// Unpack returns the nineteen elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]) Unpack() (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) {
	return t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q, t.R, t.S
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q, t.R, t.S)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F, t.G, t.H, t.I, t.J, t.K, t.L, t.M, t.N, t.O, t.P, t.Q, t.R, t.S}
}
