// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple2 provides a simple, general-purpose tuple type for holding two ordered values.
package tuple2

import "fmt"

// Tuple is a generic container that holds exactly two elements.
type Tuple[A, B any] struct {
	A A
	B B
}

// Pack creates a new Tuple containing the two supplied values.
func Pack[A, B any](a A, b B) Tuple[A, B] {
	return Tuple[A, B]{
		A: a, B: b,
	}
}

// Unpack returns the two elements contained in the tuple.
func (t Tuple[A, B]) Unpack() (A, B) {
	return t.A, t.B
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B]) String() string {
	return fmt.Sprintf("(%v, %v)", t.A, t.B)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B]) ToSlice() []any {
	return []any{t.A, t.B}
}
