// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple2getter

package tuple2

// GetA returns t.A.
func (t Tuple[A, B]) GetA() A { return t.A }

// GetB returns t.B.
func (t Tuple[A, B]) GetB() B { return t.B }
