// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build go1.22

package tuple2

import "cmp"

// Compare performs a lexicographical comparison of two tuples, comparing elements in order: A, then B.
func Compare[A, B cmp.Ordered](a, b Tuple[A, B]) int {
	if c := cmp.Compare(a.A, b.A); c != 0 {
		return c
	}
	return cmp.Compare(a.B, b.B)
}
