// Code generated by gen-tuple; DO NOT EDIT.

// Package tuple6 provides a simple, general-purpose tuple type for holding six ordered values.
package tuple6

import "fmt"

// Tuple is a generic container that holds exactly six elements.
type Tuple[A, B, C, D, E, F any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
}

// Pack creates a new Tuple containing the six supplied values.
func Pack[A, B, C, D, E, F any](a A, b B, c C, d D, e E, f F) Tuple[A, B, C, D, E, F] {
	return Tuple[A, B, C, D, E, F]{
		A: a, B: b, C: c, D: d, E: e, F: f,
	}
}

// Unpack returns the six elements contained in the tuple.
func (t Tuple[A, B, C, D, E, F]) Unpack() (A, B, C, D, E, F) {
	return t.A, t.B, t.C, t.D, t.E, t.F
}

// String returns the string representatioon of the tuple.
func (t Tuple[A, B, C, D, E, F]) String() string {
	return fmt.Sprintf("(%v, %v, %v, %v, %v, %v)", t.A, t.B, t.C, t.D, t.E, t.F)
}

// ToSlice converts the tuple elements into a slice of any.
func (t Tuple[A, B, C, D, E, F]) ToSlice() []any {
	return []any{t.A, t.B, t.C, t.D, t.E, t.F}
}
