// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build go1.22

package tuple6

import "cmp"

// Compare performs a lexicographical comparison of two tuples, comparing elements in order: A, then B, then C, then D, then E, then F.
func Compare[A, B, C, D, E, F cmp.Ordered](a, b Tuple[A, B, C, D, E, F]) int {
	if c := cmp.Compare(a.A, b.A); c != 0 {
		return c
	}
	if c := cmp.Compare(a.B, b.B); c != 0 {
		return c
	}
	if c := cmp.Compare(a.C, b.C); c != 0 {
		return c
	}
	if c := cmp.Compare(a.D, b.D); c != 0 {
		return c
	}
	if c := cmp.Compare(a.E, b.E); c != 0 {
		return c
	}
	return cmp.Compare(a.F, b.F)
}
