// Code generated by gen-tuple; DO NOT EDIT.
//
//go:build !notuplegetter || tuple23getter

package tuple23

// GetA returns t.A.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetA() A {
	return t.A
}

// GetB returns t.B.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetB() B {
	return t.B
}

// GetC returns t.C.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetC() C {
	return t.C
}

// GetD returns t.D.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetD() D {
	return t.D
}

// GetE returns t.E.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetE() E {
	return t.E
}

// GetF returns t.F.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetF() F {
	return t.F
}

// GetG returns t.G.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetG() G {
	return t.G
}

// GetH returns t.H.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetH() H {
	return t.H
}

// GetI returns t.I.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetI() I {
	return t.I
}

// GetJ returns t.J.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetJ() J {
	return t.J
}

// GetK returns t.K.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetK() K {
	return t.K
}

// GetL returns t.L.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetL() L {
	return t.L
}

// GetM returns t.M.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetM() M {
	return t.M
}

// GetN returns t.N.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetN() N {
	return t.N
}

// GetO returns t.O.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetO() O {
	return t.O
}

// GetP returns t.P.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetP() P {
	return t.P
}

// GetQ returns t.Q.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetQ() Q {
	return t.Q
}

// GetR returns t.R.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetR() R {
	return t.R
}

// GetS returns t.S.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetS() S {
	return t.S
}

// GetT returns t.T.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetT() T {
	return t.T
}

// GetU returns t.U.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetU() U {
	return t.U
}

// GetV returns t.V.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetV() V {
	return t.V
}

// GetW returns t.W.
func (t Tuple[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]) GetW() W {
	return t.W
}
